version: "3.8" # docker-composeのバージョン
services: # services配下に各コンテナの情報を記載する
  app: # golangのコンテナ
    container_name: app_go
    build: # Dockerfileのあるディレクトリのパスを指定する
      context: . # 起点となるディレクトリ
      dockerfile: ./build/package/go/Dockerfile
    depends_on: # 依存先のサービス名
      - db
    volumes: # マウント元と先を指定
      - .:/go/src/app
    environment:
      - TZ=Asia/Tokyo
    tty: true # コンテナの永続化
    ports: # (ホストマシン):(コンテナ内)でポートをマッピング
      - 7000:7000
  db:
    container_name: db_mysql # mysqlのホスト名となる。Docker内ではDSNのホストにこれを指定する
    build: # Dockerfileのあるディレクトリのパスを指定する
      context: . # 起点となるディレクトリ
      dockerfile: ./build/package/mysql/Dockerfile
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_USER=sftsys
      - MYSQL_PASSWORD=fortwo42
      - MYSQL_ROOT_PASSWORD=root42
      - MYSQL_DATABASE=inventory_control
    volumes:
      - ./build/package/mysql/data:/var/lib/mysql
      - ./build/package/mysql/init:/docker-entrypoint-initdb.d
      - ./build/package/mysql/log:/var/log/mysql
      - ./build/package/mysql/conf:/etc/mysql/conf.d
    ports: # MySQLのデフォルトポートは3306
      - 3316:3306
    tty: true
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db_gui
    depends_on: # 依存先のサービス名
      - db
    environment:
      - PMA_HOST=db # 接続先のサービス名
    ports: # Apacheはデフォルトで80をLISTENしている
      - 8090:80
    tty: true
    networks:
      - default