/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// BooksAPIRouter defines the required methods for binding the api requests to a responses for the BooksAPI
// The BooksAPIRouter implementation should parse necessary information from the http request,
// pass the data to a BooksAPIServicer to perform the required actions, then write the service results to the http response.
type BooksAPIRouter interface { 
	Call14d04cd3a807843d383b87ccfca3da7b(http.ResponseWriter, *http.Request)
	Call24c56c274fc27bd118b5dfc62fbf0c3e(http.ResponseWriter, *http.Request)
}
// BooksInfoAPIRouter defines the required methods for binding the api requests to a responses for the BooksInfoAPI
// The BooksInfoAPIRouter implementation should parse necessary information from the http request,
// pass the data to a BooksInfoAPIServicer to perform the required actions, then write the service results to the http response.
type BooksInfoAPIRouter interface { 
	Aefd1f8354eca94d504850ef936b3fb4(http.ResponseWriter, *http.Request)
	Call0c3283a323f1a4a3e81dbd5915be7518(http.ResponseWriter, *http.Request)
	Call2f9e356b188781492d6410beee2297c6(http.ResponseWriter, *http.Request)
	Call57b90f97a8a076e500862e557256c7aa(http.ResponseWriter, *http.Request)
	E98599424d7afa9076f6f9f4df52e4e4(http.ResponseWriter, *http.Request)
}
// BooksStocksAPIRouter defines the required methods for binding the api requests to a responses for the BooksStocksAPI
// The BooksStocksAPIRouter implementation should parse necessary information from the http request,
// pass the data to a BooksStocksAPIServicer to perform the required actions, then write the service results to the http response.
type BooksStocksAPIRouter interface { 
	Call45a5cfdaf4972cd73313133082ca0d26(http.ResponseWriter, *http.Request)
	Call46c90e16b416e254ed79948864ae87aa(http.ResponseWriter, *http.Request)
	D1c6d70f9a35791050b5da811f1abda1(http.ResponseWriter, *http.Request)
	Dc7eef146e782e14cddc076176ff04c4(http.ResponseWriter, *http.Request)
	Ecc649eea287e26856100c11f96bb3b9(http.ResponseWriter, *http.Request)
}
// ContactsAPIRouter defines the required methods for binding the api requests to a responses for the ContactsAPI
// The ContactsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ContactsAPIServicer to perform the required actions, then write the service results to the http response.
type ContactsAPIRouter interface { 
	Adc814a54ff3a1fdc424293b19ffe8a7(http.ResponseWriter, *http.Request)
	Bc8b0b91abd89481c321fcdb966dc355(http.ResponseWriter, *http.Request)
	Call4c4e002507e3a53acc022b210aad20ac(http.ResponseWriter, *http.Request)
	Call77b53a0b0cb97bf04eafa192e4cbac4e(http.ResponseWriter, *http.Request)
	E670331f5da6af785062a857ec92def2(http.ResponseWriter, *http.Request)
}
// NewsAPIRouter defines the required methods for binding the api requests to a responses for the NewsAPI
// The NewsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a NewsAPIServicer to perform the required actions, then write the service results to the http response.
type NewsAPIRouter interface { 
	Bbe79a918bfbb58bc46ed74b43e9b986(http.ResponseWriter, *http.Request)
	Call21b84dbdd75fd20b9c9ddb9b9e68f0a1(http.ResponseWriter, *http.Request)
	Call25ea273290c6cb379ab85e08ff4fadfc(http.ResponseWriter, *http.Request)
	D6a12c2e3b4ea9ab588ba9b1cb14748f(http.ResponseWriter, *http.Request)
	Eb815321a4dd395639d4aeef25d9a45c(http.ResponseWriter, *http.Request)
}
// OrdersCustomersAPIRouter defines the required methods for binding the api requests to a responses for the OrdersCustomersAPI
// The OrdersCustomersAPIRouter implementation should parse necessary information from the http request,
// pass the data to a OrdersCustomersAPIServicer to perform the required actions, then write the service results to the http response.
type OrdersCustomersAPIRouter interface { 
	A0a94057f0311e2193b5897f80221470(http.ResponseWriter, *http.Request)
	Call4dd012aac3be308644f1e2e152f92c19(http.ResponseWriter, *http.Request)
	Call5217a452519ec6ef916c6a3e2f4070dc(http.ResponseWriter, *http.Request)
	Call5608eff2ef8984e0b7447765f27595aa(http.ResponseWriter, *http.Request)
	Call75e0485900f170d2424fdeadf59b0752(http.ResponseWriter, *http.Request)
}
// OrdersItemsAPIRouter defines the required methods for binding the api requests to a responses for the OrdersItemsAPI
// The OrdersItemsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a OrdersItemsAPIServicer to perform the required actions, then write the service results to the http response.
type OrdersItemsAPIRouter interface { 
	B2909cc3849277b1d5345ccb4205c71d(http.ResponseWriter, *http.Request)
	Call0b2a7a56e7d5c2c49b7d11bdb0f48f5c(http.ResponseWriter, *http.Request)
	Call6d397dbc3afd3a3f44e4cc08820e0921(http.ResponseWriter, *http.Request)
	Call89fde6ad08076b992c521fb7c680e29e(http.ResponseWriter, *http.Request)
	Call8bee2e95aba24db3af9b2bc7b5a53f0d(http.ResponseWriter, *http.Request)
}
// OrdersPaymentsAPIRouter defines the required methods for binding the api requests to a responses for the OrdersPaymentsAPI
// The OrdersPaymentsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a OrdersPaymentsAPIServicer to perform the required actions, then write the service results to the http response.
type OrdersPaymentsAPIRouter interface { 
	Call231e4438ab66e1f3ba4205adf67e0df7(http.ResponseWriter, *http.Request)
	Call41c8a438add65c3a1a6f1f7f0efeeea3(http.ResponseWriter, *http.Request)
	Call52140bdaf9965edfc692b030a9f1898f(http.ResponseWriter, *http.Request)
	E7043bcd7e8fc712b2e3a6516f1b8ca8(http.ResponseWriter, *http.Request)
	Ed63e750658440b279ee8040dc02aba5(http.ResponseWriter, *http.Request)
}
// TypesBranchesAPIRouter defines the required methods for binding the api requests to a responses for the TypesBranchesAPI
// The TypesBranchesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a TypesBranchesAPIServicer to perform the required actions, then write the service results to the http response.
type TypesBranchesAPIRouter interface { 
	Call4f16c2a000161aa01c071b5beabaa1f2(http.ResponseWriter, *http.Request)
	Call97af74bfee220c89b0c0c5700fd29b99(http.ResponseWriter, *http.Request)
	Call98726087136b83ce1a215021e6eb76de(http.ResponseWriter, *http.Request)
	Ce050dbe8f9dcf8a1411581387496db6(http.ResponseWriter, *http.Request)
	E33a8a3abd11b078e164c05b62246e43(http.ResponseWriter, *http.Request)
}
// TypesGenresAPIRouter defines the required methods for binding the api requests to a responses for the TypesGenresAPI
// The TypesGenresAPIRouter implementation should parse necessary information from the http request,
// pass the data to a TypesGenresAPIServicer to perform the required actions, then write the service results to the http response.
type TypesGenresAPIRouter interface { 
	Call32a2a32ec50d514a9cc3ca51fb2d6578(http.ResponseWriter, *http.Request)
	Call5876eb953745b47325ca0277455f8885(http.ResponseWriter, *http.Request)
	Call6e1cdb613ad44750c97159198eac2c2e(http.ResponseWriter, *http.Request)
	Call70509fad3bfe1e67a2caf35fe9ddcd88(http.ResponseWriter, *http.Request)
	Call8ecb93fe6d9f820f901f57aaca0c8650(http.ResponseWriter, *http.Request)
}
// TypesOrdersStatesAPIRouter defines the required methods for binding the api requests to a responses for the TypesOrdersStatesAPI
// The TypesOrdersStatesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a TypesOrdersStatesAPIServicer to perform the required actions, then write the service results to the http response.
type TypesOrdersStatesAPIRouter interface { 
	Call02b2536d5626b2b69c4eb31a6420a222(http.ResponseWriter, *http.Request)
	Call035007899d1aeec37cb670bb3c8a4865(http.ResponseWriter, *http.Request)
	Call629ceee33a2f3da61afd7c4b1e462219(http.ResponseWriter, *http.Request)
	F264dd50d2da88f988e3a8e7c592d301(http.ResponseWriter, *http.Request)
	F8e23ef739c0f341106a112ecde4ad7e(http.ResponseWriter, *http.Request)
}
// TypesPaymentsAPIRouter defines the required methods for binding the api requests to a responses for the TypesPaymentsAPI
// The TypesPaymentsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a TypesPaymentsAPIServicer to perform the required actions, then write the service results to the http response.
type TypesPaymentsAPIRouter interface { 
	Call15eb6d8e179f295d0df87be744c28155(http.ResponseWriter, *http.Request)
	Call9dd9af2fc19d3f1e1688cf1b0528218b(http.ResponseWriter, *http.Request)
	E757690d6c96a1463bd2f8fce9b45b12(http.ResponseWriter, *http.Request)
	E83a182945610fbcf279008b97e0de46(http.ResponseWriter, *http.Request)
	Eaf58772b330330fc4d41fc0e8b3b40f(http.ResponseWriter, *http.Request)
}
// TypesReceivesAPIRouter defines the required methods for binding the api requests to a responses for the TypesReceivesAPI
// The TypesReceivesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a TypesReceivesAPIServicer to perform the required actions, then write the service results to the http response.
type TypesReceivesAPIRouter interface { 
	B1a600a99289da180209079339415e49(http.ResponseWriter, *http.Request)
	C1543df8694acb50827b80eb08cd5b4a(http.ResponseWriter, *http.Request)
	Call0417ea5e25bfb8fd8ee49856f17016fa(http.ResponseWriter, *http.Request)
	Call50090e82cc0eacb3d7b613a9ff868b17(http.ResponseWriter, *http.Request)
	F84e4922d0eeb8c8d92bcbf48af06a74(http.ResponseWriter, *http.Request)
}


// BooksAPIServicer defines the api actions for the BooksAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type BooksAPIServicer interface { 
	Call14d04cd3a807843d383b87ccfca3da7b(context.Context, int32, string, int32, int32) (ImplResponse, error)
	Call24c56c274fc27bd118b5dfc62fbf0c3e(context.Context, int32, string, string, string, string, string, string) (ImplResponse, error)
}


// BooksInfoAPIServicer defines the api actions for the BooksInfoAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type BooksInfoAPIServicer interface { 
	Aefd1f8354eca94d504850ef936b3fb4(context.Context, string) (ImplResponse, error)
	Call0c3283a323f1a4a3e81dbd5915be7518(context.Context, BookInfo) (ImplResponse, error)
	Call2f9e356b188781492d6410beee2297c6(context.Context) (ImplResponse, error)
	Call57b90f97a8a076e500862e557256c7aa(context.Context, string, BookInfo) (ImplResponse, error)
	E98599424d7afa9076f6f9f4df52e4e4(context.Context, string) (ImplResponse, error)
}


// BooksStocksAPIServicer defines the api actions for the BooksStocksAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type BooksStocksAPIServicer interface { 
	Call45a5cfdaf4972cd73313133082ca0d26(context.Context, string) (ImplResponse, error)
	Call46c90e16b416e254ed79948864ae87aa(context.Context) (ImplResponse, error)
	D1c6d70f9a35791050b5da811f1abda1(context.Context, string) (ImplResponse, error)
	Dc7eef146e782e14cddc076176ff04c4(context.Context, string, BookStock) (ImplResponse, error)
	Ecc649eea287e26856100c11f96bb3b9(context.Context, BookStock) (ImplResponse, error)
}


// ContactsAPIServicer defines the api actions for the ContactsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ContactsAPIServicer interface { 
	Adc814a54ff3a1fdc424293b19ffe8a7(context.Context, string, Contact) (ImplResponse, error)
	Bc8b0b91abd89481c321fcdb966dc355(context.Context, string) (ImplResponse, error)
	Call4c4e002507e3a53acc022b210aad20ac(context.Context, string) (ImplResponse, error)
	Call77b53a0b0cb97bf04eafa192e4cbac4e(context.Context, Contact) (ImplResponse, error)
	E670331f5da6af785062a857ec92def2(context.Context) (ImplResponse, error)
}


// NewsAPIServicer defines the api actions for the NewsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type NewsAPIServicer interface { 
	Bbe79a918bfbb58bc46ed74b43e9b986(context.Context, string) (ImplResponse, error)
	Call21b84dbdd75fd20b9c9ddb9b9e68f0a1(context.Context) (ImplResponse, error)
	Call25ea273290c6cb379ab85e08ff4fadfc(context.Context, string, News) (ImplResponse, error)
	D6a12c2e3b4ea9ab588ba9b1cb14748f(context.Context, News) (ImplResponse, error)
	Eb815321a4dd395639d4aeef25d9a45c(context.Context, string) (ImplResponse, error)
}


// OrdersCustomersAPIServicer defines the api actions for the OrdersCustomersAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type OrdersCustomersAPIServicer interface { 
	A0a94057f0311e2193b5897f80221470(context.Context, string, OrderCustomer) (ImplResponse, error)
	Call4dd012aac3be308644f1e2e152f92c19(context.Context, string) (ImplResponse, error)
	Call5217a452519ec6ef916c6a3e2f4070dc(context.Context) (ImplResponse, error)
	Call5608eff2ef8984e0b7447765f27595aa(context.Context, string) (ImplResponse, error)
	Call75e0485900f170d2424fdeadf59b0752(context.Context, OrderCustomer) (ImplResponse, error)
}


// OrdersItemsAPIServicer defines the api actions for the OrdersItemsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type OrdersItemsAPIServicer interface { 
	B2909cc3849277b1d5345ccb4205c71d(context.Context, OrderItem) (ImplResponse, error)
	Call0b2a7a56e7d5c2c49b7d11bdb0f48f5c(context.Context, string) (ImplResponse, error)
	Call6d397dbc3afd3a3f44e4cc08820e0921(context.Context, string) (ImplResponse, error)
	Call89fde6ad08076b992c521fb7c680e29e(context.Context) (ImplResponse, error)
	Call8bee2e95aba24db3af9b2bc7b5a53f0d(context.Context, string, OrderItem) (ImplResponse, error)
}


// OrdersPaymentsAPIServicer defines the api actions for the OrdersPaymentsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type OrdersPaymentsAPIServicer interface { 
	Call231e4438ab66e1f3ba4205adf67e0df7(context.Context, OrderPayment) (ImplResponse, error)
	Call41c8a438add65c3a1a6f1f7f0efeeea3(context.Context, string) (ImplResponse, error)
	Call52140bdaf9965edfc692b030a9f1898f(context.Context) (ImplResponse, error)
	E7043bcd7e8fc712b2e3a6516f1b8ca8(context.Context, string, OrderPayment) (ImplResponse, error)
	Ed63e750658440b279ee8040dc02aba5(context.Context, string) (ImplResponse, error)
}


// TypesBranchesAPIServicer defines the api actions for the TypesBranchesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type TypesBranchesAPIServicer interface { 
	Call4f16c2a000161aa01c071b5beabaa1f2(context.Context, string) (ImplResponse, error)
	Call97af74bfee220c89b0c0c5700fd29b99(context.Context) (ImplResponse, error)
	Call98726087136b83ce1a215021e6eb76de(context.Context, string, TypeBranch) (ImplResponse, error)
	Ce050dbe8f9dcf8a1411581387496db6(context.Context, TypeBranch) (ImplResponse, error)
	E33a8a3abd11b078e164c05b62246e43(context.Context, string) (ImplResponse, error)
}


// TypesGenresAPIServicer defines the api actions for the TypesGenresAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type TypesGenresAPIServicer interface { 
	Call32a2a32ec50d514a9cc3ca51fb2d6578(context.Context, string, TypeGenre) (ImplResponse, error)
	Call5876eb953745b47325ca0277455f8885(context.Context, TypeGenre) (ImplResponse, error)
	Call6e1cdb613ad44750c97159198eac2c2e(context.Context) (ImplResponse, error)
	Call70509fad3bfe1e67a2caf35fe9ddcd88(context.Context, string) (ImplResponse, error)
	Call8ecb93fe6d9f820f901f57aaca0c8650(context.Context, string) (ImplResponse, error)
}


// TypesOrdersStatesAPIServicer defines the api actions for the TypesOrdersStatesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type TypesOrdersStatesAPIServicer interface { 
	Call02b2536d5626b2b69c4eb31a6420a222(context.Context, TypeOrderState) (ImplResponse, error)
	Call035007899d1aeec37cb670bb3c8a4865(context.Context, string) (ImplResponse, error)
	Call629ceee33a2f3da61afd7c4b1e462219(context.Context) (ImplResponse, error)
	F264dd50d2da88f988e3a8e7c592d301(context.Context, string) (ImplResponse, error)
	F8e23ef739c0f341106a112ecde4ad7e(context.Context, string, TypeOrderState) (ImplResponse, error)
}


// TypesPaymentsAPIServicer defines the api actions for the TypesPaymentsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type TypesPaymentsAPIServicer interface { 
	Call15eb6d8e179f295d0df87be744c28155(context.Context, string) (ImplResponse, error)
	Call9dd9af2fc19d3f1e1688cf1b0528218b(context.Context, string, TypePayment) (ImplResponse, error)
	E757690d6c96a1463bd2f8fce9b45b12(context.Context, TypePayment) (ImplResponse, error)
	E83a182945610fbcf279008b97e0de46(context.Context, string) (ImplResponse, error)
	Eaf58772b330330fc4d41fc0e8b3b40f(context.Context) (ImplResponse, error)
}


// TypesReceivesAPIServicer defines the api actions for the TypesReceivesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type TypesReceivesAPIServicer interface { 
	B1a600a99289da180209079339415e49(context.Context, string) (ImplResponse, error)
	C1543df8694acb50827b80eb08cd5b4a(context.Context, string, TypeReceive) (ImplResponse, error)
	Call0417ea5e25bfb8fd8ee49856f17016fa(context.Context) (ImplResponse, error)
	Call50090e82cc0eacb3d7b613a9ff868b17(context.Context, TypeReceive) (ImplResponse, error)
	F84e4922d0eeb8c8d92bcbf48af06a74(context.Context, string) (ImplResponse, error)
}
