/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// TypesOrdersStatesAPIService is a service that implements the logic for the TypesOrdersStatesAPIServicer
// This service should implement the business logic for every endpoint for the TypesOrdersStatesAPI API.
// Include any external packages or services that will be required by this service.
type TypesOrdersStatesAPIService struct {
}

// NewTypesOrdersStatesAPIService creates a default api service
func NewTypesOrdersStatesAPIService() TypesOrdersStatesAPIServicer {
	return &TypesOrdersStatesAPIService{}
}

// Call02b2536d5626b2b69c4eb31a6420a222 - Create a new types_orders_states
func (s *TypesOrdersStatesAPIService) Call02b2536d5626b2b69c4eb31a6420a222(ctx context.Context, typeOrderState TypeOrderState) (ImplResponse, error) {
	// TODO - update Call02b2536d5626b2b69c4eb31a6420a222 with the required logic for this service method.
	// Add api_types_orders_states_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, TypeOrderState{}) or use other options such as http.Ok ...
	// return Response(201, TypeOrderState{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call02b2536d5626b2b69c4eb31a6420a222 method not implemented")
}

// Call035007899d1aeec37cb670bb3c8a4865 - Delete a specific types_orders_states by ID
func (s *TypesOrdersStatesAPIService) Call035007899d1aeec37cb670bb3c8a4865(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call035007899d1aeec37cb670bb3c8a4865 with the required logic for this service method.
	// Add api_types_orders_states_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call035007899d1aeec37cb670bb3c8a4865 method not implemented")
}

// Call629ceee33a2f3da61afd7c4b1e462219 - Get a list of types_orders_states
func (s *TypesOrdersStatesAPIService) Call629ceee33a2f3da61afd7c4b1e462219(ctx context.Context) (ImplResponse, error) {
	// TODO - update Call629ceee33a2f3da61afd7c4b1e462219 with the required logic for this service method.
	// Add api_types_orders_states_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []TypeOrderState{}) or use other options such as http.Ok ...
	// return Response(200, []TypeOrderState{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call629ceee33a2f3da61afd7c4b1e462219 method not implemented")
}

// F264dd50d2da88f988e3a8e7c592d301 - Get a specific types_orders_states by ID
func (s *TypesOrdersStatesAPIService) F264dd50d2da88f988e3a8e7c592d301(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update F264dd50d2da88f988e3a8e7c592d301 with the required logic for this service method.
	// Add api_types_orders_states_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypeOrderState{}) or use other options such as http.Ok ...
	// return Response(200, TypeOrderState{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("F264dd50d2da88f988e3a8e7c592d301 method not implemented")
}

// F8e23ef739c0f341106a112ecde4ad7e - Update a specific types_orders_states by ID
func (s *TypesOrdersStatesAPIService) F8e23ef739c0f341106a112ecde4ad7e(ctx context.Context, id string, typeOrderState TypeOrderState) (ImplResponse, error) {
	// TODO - update F8e23ef739c0f341106a112ecde4ad7e with the required logic for this service method.
	// Add api_types_orders_states_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypeOrderState{}) or use other options such as http.Ok ...
	// return Response(200, TypeOrderState{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("F8e23ef739c0f341106a112ecde4ad7e method not implemented")
}
