/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// ContactsAPIController binds http requests to an api service and writes the service results to the http response
type ContactsAPIController struct {
	service ContactsAPIServicer
	errorHandler ErrorHandler
}

// ContactsAPIOption for how the controller is set up.
type ContactsAPIOption func(*ContactsAPIController)

// WithContactsAPIErrorHandler inject ErrorHandler into controller
func WithContactsAPIErrorHandler(h ErrorHandler) ContactsAPIOption {
	return func(c *ContactsAPIController) {
		c.errorHandler = h
	}
}

// NewContactsAPIController creates a default api controller
func NewContactsAPIController(s ContactsAPIServicer, opts ...ContactsAPIOption) Router {
	controller := &ContactsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ContactsAPIController
func (c *ContactsAPIController) Routes() Routes {
	return Routes{
		"Adc814a54ff3a1fdc424293b19ffe8a7": Route{
			strings.ToUpper("Put"),
			"/api/contacts/{id}",
			c.Adc814a54ff3a1fdc424293b19ffe8a7,
		},
		"Bc8b0b91abd89481c321fcdb966dc355": Route{
			strings.ToUpper("Delete"),
			"/api/contacts/{id}",
			c.Bc8b0b91abd89481c321fcdb966dc355,
		},
		"Call4c4e002507e3a53acc022b210aad20ac": Route{
			strings.ToUpper("Get"),
			"/api/contacts/{id}",
			c.Call4c4e002507e3a53acc022b210aad20ac,
		},
		"Call77b53a0b0cb97bf04eafa192e4cbac4e": Route{
			strings.ToUpper("Post"),
			"/api/contacts",
			c.Call77b53a0b0cb97bf04eafa192e4cbac4e,
		},
		"E670331f5da6af785062a857ec92def2": Route{
			strings.ToUpper("Get"),
			"/api/contacts",
			c.E670331f5da6af785062a857ec92def2,
		},
	}
}

// Adc814a54ff3a1fdc424293b19ffe8a7 - Update a specific contact by ID
func (c *ContactsAPIController) Adc814a54ff3a1fdc424293b19ffe8a7(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	contactParam := Contact{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&contactParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertContactRequired(contactParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertContactConstraints(contactParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Adc814a54ff3a1fdc424293b19ffe8a7(r.Context(), idParam, contactParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Bc8b0b91abd89481c321fcdb966dc355 - Delete a specific contact by ID
func (c *ContactsAPIController) Bc8b0b91abd89481c321fcdb966dc355(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Bc8b0b91abd89481c321fcdb966dc355(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call4c4e002507e3a53acc022b210aad20ac - Get a specific contact by ID
func (c *ContactsAPIController) Call4c4e002507e3a53acc022b210aad20ac(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Call4c4e002507e3a53acc022b210aad20ac(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call77b53a0b0cb97bf04eafa192e4cbac4e - Create a new contact
func (c *ContactsAPIController) Call77b53a0b0cb97bf04eafa192e4cbac4e(w http.ResponseWriter, r *http.Request) {
	contactParam := Contact{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&contactParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertContactRequired(contactParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertContactConstraints(contactParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call77b53a0b0cb97bf04eafa192e4cbac4e(r.Context(), contactParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// E670331f5da6af785062a857ec92def2 - Get a list of contacts
func (c *ContactsAPIController) E670331f5da6af785062a857ec92def2(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.E670331f5da6af785062a857ec92def2(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
