/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// BooksInfoAPIController binds http requests to an api service and writes the service results to the http response
type BooksInfoAPIController struct {
	service BooksInfoAPIServicer
	errorHandler ErrorHandler
}

// BooksInfoAPIOption for how the controller is set up.
type BooksInfoAPIOption func(*BooksInfoAPIController)

// WithBooksInfoAPIErrorHandler inject ErrorHandler into controller
func WithBooksInfoAPIErrorHandler(h ErrorHandler) BooksInfoAPIOption {
	return func(c *BooksInfoAPIController) {
		c.errorHandler = h
	}
}

// NewBooksInfoAPIController creates a default api controller
func NewBooksInfoAPIController(s BooksInfoAPIServicer, opts ...BooksInfoAPIOption) Router {
	controller := &BooksInfoAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the BooksInfoAPIController
func (c *BooksInfoAPIController) Routes() Routes {
	return Routes{
		"Aefd1f8354eca94d504850ef936b3fb4": Route{
			strings.ToUpper("Get"),
			"/api/books_info/{id}",
			c.Aefd1f8354eca94d504850ef936b3fb4,
		},
		"Call0c3283a323f1a4a3e81dbd5915be7518": Route{
			strings.ToUpper("Post"),
			"/api/books_info",
			c.Call0c3283a323f1a4a3e81dbd5915be7518,
		},
		"Call2f9e356b188781492d6410beee2297c6": Route{
			strings.ToUpper("Get"),
			"/api/books_info",
			c.Call2f9e356b188781492d6410beee2297c6,
		},
		"Call57b90f97a8a076e500862e557256c7aa": Route{
			strings.ToUpper("Put"),
			"/api/books_info/{id}",
			c.Call57b90f97a8a076e500862e557256c7aa,
		},
		"E98599424d7afa9076f6f9f4df52e4e4": Route{
			strings.ToUpper("Delete"),
			"/api/books_info/{id}",
			c.E98599424d7afa9076f6f9f4df52e4e4,
		},
	}
}

// Aefd1f8354eca94d504850ef936b3fb4 - Get a specific books_info by ID
func (c *BooksInfoAPIController) Aefd1f8354eca94d504850ef936b3fb4(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Aefd1f8354eca94d504850ef936b3fb4(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call0c3283a323f1a4a3e81dbd5915be7518 - Create a new books_info
func (c *BooksInfoAPIController) Call0c3283a323f1a4a3e81dbd5915be7518(w http.ResponseWriter, r *http.Request) {
	bookInfoParam := BookInfo{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bookInfoParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBookInfoRequired(bookInfoParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBookInfoConstraints(bookInfoParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call0c3283a323f1a4a3e81dbd5915be7518(r.Context(), bookInfoParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call2f9e356b188781492d6410beee2297c6 - Get a list of books_info
func (c *BooksInfoAPIController) Call2f9e356b188781492d6410beee2297c6(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Call2f9e356b188781492d6410beee2297c6(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call57b90f97a8a076e500862e557256c7aa - Update a specific books_info by ID
func (c *BooksInfoAPIController) Call57b90f97a8a076e500862e557256c7aa(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	bookInfoParam := BookInfo{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bookInfoParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBookInfoRequired(bookInfoParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBookInfoConstraints(bookInfoParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call57b90f97a8a076e500862e557256c7aa(r.Context(), idParam, bookInfoParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// E98599424d7afa9076f6f9f4df52e4e4 - Delete a specific books_info by ID
func (c *BooksInfoAPIController) E98599424d7afa9076f6f9f4df52e4e4(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.E98599424d7afa9076f6f9f4df52e4e4(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
