/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// TypesBranchesAPIService is a service that implements the logic for the TypesBranchesAPIServicer
// This service should implement the business logic for every endpoint for the TypesBranchesAPI API.
// Include any external packages or services that will be required by this service.
type TypesBranchesAPIService struct {
}

// NewTypesBranchesAPIService creates a default api service
func NewTypesBranchesAPIService() TypesBranchesAPIServicer {
	return &TypesBranchesAPIService{}
}

// Call4f16c2a000161aa01c071b5beabaa1f2 - Delete a specific types_branches by ID
func (s *TypesBranchesAPIService) Call4f16c2a000161aa01c071b5beabaa1f2(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call4f16c2a000161aa01c071b5beabaa1f2 with the required logic for this service method.
	// Add api_types_branches_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call4f16c2a000161aa01c071b5beabaa1f2 method not implemented")
}

// Call97af74bfee220c89b0c0c5700fd29b99 - Get a list of types_branches
func (s *TypesBranchesAPIService) Call97af74bfee220c89b0c0c5700fd29b99(ctx context.Context) (ImplResponse, error) {
	// TODO - update Call97af74bfee220c89b0c0c5700fd29b99 with the required logic for this service method.
	// Add api_types_branches_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []TypeBranch{}) or use other options such as http.Ok ...
	// return Response(200, []TypeBranch{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call97af74bfee220c89b0c0c5700fd29b99 method not implemented")
}

// Call98726087136b83ce1a215021e6eb76de - Update a specific types_branches by ID
func (s *TypesBranchesAPIService) Call98726087136b83ce1a215021e6eb76de(ctx context.Context, id string, typeBranch TypeBranch) (ImplResponse, error) {
	// TODO - update Call98726087136b83ce1a215021e6eb76de with the required logic for this service method.
	// Add api_types_branches_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypeBranch{}) or use other options such as http.Ok ...
	// return Response(200, TypeBranch{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call98726087136b83ce1a215021e6eb76de method not implemented")
}

// Ce050dbe8f9dcf8a1411581387496db6 - Create a new types_branches
func (s *TypesBranchesAPIService) Ce050dbe8f9dcf8a1411581387496db6(ctx context.Context, typeBranch TypeBranch) (ImplResponse, error) {
	// TODO - update Ce050dbe8f9dcf8a1411581387496db6 with the required logic for this service method.
	// Add api_types_branches_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, TypeBranch{}) or use other options such as http.Ok ...
	// return Response(201, TypeBranch{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Ce050dbe8f9dcf8a1411581387496db6 method not implemented")
}

// E33a8a3abd11b078e164c05b62246e43 - Get a specific types_branches by ID
func (s *TypesBranchesAPIService) E33a8a3abd11b078e164c05b62246e43(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update E33a8a3abd11b078e164c05b62246e43 with the required logic for this service method.
	// Add api_types_branches_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypeBranch{}) or use other options such as http.Ok ...
	// return Response(200, TypeBranch{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("E33a8a3abd11b078e164c05b62246e43 method not implemented")
}
