/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// OrdersCustomersAPIService is a service that implements the logic for the OrdersCustomersAPIServicer
// This service should implement the business logic for every endpoint for the OrdersCustomersAPI API.
// Include any external packages or services that will be required by this service.
type OrdersCustomersAPIService struct {
}

// NewOrdersCustomersAPIService creates a default api service
func NewOrdersCustomersAPIService() OrdersCustomersAPIServicer {
	return &OrdersCustomersAPIService{}
}

// A0a94057f0311e2193b5897f80221470 - Update a specific orders_customers by ID
func (s *OrdersCustomersAPIService) A0a94057f0311e2193b5897f80221470(ctx context.Context, id string, orderCustomer OrderCustomer) (ImplResponse, error) {
	// TODO - update A0a94057f0311e2193b5897f80221470 with the required logic for this service method.
	// Add api_orders_customers_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderCustomer{}) or use other options such as http.Ok ...
	// return Response(200, OrderCustomer{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("A0a94057f0311e2193b5897f80221470 method not implemented")
}

// Call4dd012aac3be308644f1e2e152f92c19 - Get a specific orders_customers by ID
func (s *OrdersCustomersAPIService) Call4dd012aac3be308644f1e2e152f92c19(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call4dd012aac3be308644f1e2e152f92c19 with the required logic for this service method.
	// Add api_orders_customers_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderCustomer{}) or use other options such as http.Ok ...
	// return Response(200, OrderCustomer{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call4dd012aac3be308644f1e2e152f92c19 method not implemented")
}

// Call5217a452519ec6ef916c6a3e2f4070dc - Get a list of orders_customers
func (s *OrdersCustomersAPIService) Call5217a452519ec6ef916c6a3e2f4070dc(ctx context.Context) (ImplResponse, error) {
	// TODO - update Call5217a452519ec6ef916c6a3e2f4070dc with the required logic for this service method.
	// Add api_orders_customers_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []OrderCustomer{}) or use other options such as http.Ok ...
	// return Response(200, []OrderCustomer{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call5217a452519ec6ef916c6a3e2f4070dc method not implemented")
}

// Call5608eff2ef8984e0b7447765f27595aa - Delete a specific orders_customers by ID
func (s *OrdersCustomersAPIService) Call5608eff2ef8984e0b7447765f27595aa(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call5608eff2ef8984e0b7447765f27595aa with the required logic for this service method.
	// Add api_orders_customers_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call5608eff2ef8984e0b7447765f27595aa method not implemented")
}

// Call75e0485900f170d2424fdeadf59b0752 - Create a new orders_customers
func (s *OrdersCustomersAPIService) Call75e0485900f170d2424fdeadf59b0752(ctx context.Context, orderCustomer OrderCustomer) (ImplResponse, error) {
	// TODO - update Call75e0485900f170d2424fdeadf59b0752 with the required logic for this service method.
	// Add api_orders_customers_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, OrderCustomer{}) or use other options such as http.Ok ...
	// return Response(201, OrderCustomer{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call75e0485900f170d2424fdeadf59b0752 method not implemented")
}
