/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// TypesPaymentsAPIService is a service that implements the logic for the TypesPaymentsAPIServicer
// This service should implement the business logic for every endpoint for the TypesPaymentsAPI API.
// Include any external packages or services that will be required by this service.
type TypesPaymentsAPIService struct {
}

// NewTypesPaymentsAPIService creates a default api service
func NewTypesPaymentsAPIService() TypesPaymentsAPIServicer {
	return &TypesPaymentsAPIService{}
}

// Call15eb6d8e179f295d0df87be744c28155 - Get a specific types_payments by ID
func (s *TypesPaymentsAPIService) Call15eb6d8e179f295d0df87be744c28155(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call15eb6d8e179f295d0df87be744c28155 with the required logic for this service method.
	// Add api_types_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypePayment{}) or use other options such as http.Ok ...
	// return Response(200, TypePayment{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call15eb6d8e179f295d0df87be744c28155 method not implemented")
}

// Call9dd9af2fc19d3f1e1688cf1b0528218b - Update a specific types_payments by ID
func (s *TypesPaymentsAPIService) Call9dd9af2fc19d3f1e1688cf1b0528218b(ctx context.Context, id string, typePayment TypePayment) (ImplResponse, error) {
	// TODO - update Call9dd9af2fc19d3f1e1688cf1b0528218b with the required logic for this service method.
	// Add api_types_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypePayment{}) or use other options such as http.Ok ...
	// return Response(200, TypePayment{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call9dd9af2fc19d3f1e1688cf1b0528218b method not implemented")
}

// E757690d6c96a1463bd2f8fce9b45b12 - Create a new types_payments
func (s *TypesPaymentsAPIService) E757690d6c96a1463bd2f8fce9b45b12(ctx context.Context, typePayment TypePayment) (ImplResponse, error) {
	// TODO - update E757690d6c96a1463bd2f8fce9b45b12 with the required logic for this service method.
	// Add api_types_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, TypePayment{}) or use other options such as http.Ok ...
	// return Response(201, TypePayment{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("E757690d6c96a1463bd2f8fce9b45b12 method not implemented")
}

// E83a182945610fbcf279008b97e0de46 - Delete a specific types_payments by ID
func (s *TypesPaymentsAPIService) E83a182945610fbcf279008b97e0de46(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update E83a182945610fbcf279008b97e0de46 with the required logic for this service method.
	// Add api_types_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("E83a182945610fbcf279008b97e0de46 method not implemented")
}

// Eaf58772b330330fc4d41fc0e8b3b40f - Get a list of types_payments
func (s *TypesPaymentsAPIService) Eaf58772b330330fc4d41fc0e8b3b40f(ctx context.Context) (ImplResponse, error) {
	// TODO - update Eaf58772b330330fc4d41fc0e8b3b40f with the required logic for this service method.
	// Add api_types_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []TypePayment{}) or use other options such as http.Ok ...
	// return Response(200, []TypePayment{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Eaf58772b330330fc4d41fc0e8b3b40f method not implemented")
}
