/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// TypesReceivesAPIService is a service that implements the logic for the TypesReceivesAPIServicer
// This service should implement the business logic for every endpoint for the TypesReceivesAPI API.
// Include any external packages or services that will be required by this service.
type TypesReceivesAPIService struct {
}

// NewTypesReceivesAPIService creates a default api service
func NewTypesReceivesAPIService() TypesReceivesAPIServicer {
	return &TypesReceivesAPIService{}
}

// B1a600a99289da180209079339415e49 - Delete a specific types_receives by ID
func (s *TypesReceivesAPIService) B1a600a99289da180209079339415e49(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update B1a600a99289da180209079339415e49 with the required logic for this service method.
	// Add api_types_receives_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("B1a600a99289da180209079339415e49 method not implemented")
}

// C1543df8694acb50827b80eb08cd5b4a - Update a specific types_receives by ID
func (s *TypesReceivesAPIService) C1543df8694acb50827b80eb08cd5b4a(ctx context.Context, id string, typeReceive TypeReceive) (ImplResponse, error) {
	// TODO - update C1543df8694acb50827b80eb08cd5b4a with the required logic for this service method.
	// Add api_types_receives_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypeReceive{}) or use other options such as http.Ok ...
	// return Response(200, TypeReceive{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("C1543df8694acb50827b80eb08cd5b4a method not implemented")
}

// Call0417ea5e25bfb8fd8ee49856f17016fa - Get a list of types_receives
func (s *TypesReceivesAPIService) Call0417ea5e25bfb8fd8ee49856f17016fa(ctx context.Context) (ImplResponse, error) {
	// TODO - update Call0417ea5e25bfb8fd8ee49856f17016fa with the required logic for this service method.
	// Add api_types_receives_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []TypeReceive{}) or use other options such as http.Ok ...
	// return Response(200, []TypeReceive{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call0417ea5e25bfb8fd8ee49856f17016fa method not implemented")
}

// Call50090e82cc0eacb3d7b613a9ff868b17 - Create a new types_receives
func (s *TypesReceivesAPIService) Call50090e82cc0eacb3d7b613a9ff868b17(ctx context.Context, typeReceive TypeReceive) (ImplResponse, error) {
	// TODO - update Call50090e82cc0eacb3d7b613a9ff868b17 with the required logic for this service method.
	// Add api_types_receives_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, TypeReceive{}) or use other options such as http.Ok ...
	// return Response(201, TypeReceive{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call50090e82cc0eacb3d7b613a9ff868b17 method not implemented")
}

// F84e4922d0eeb8c8d92bcbf48af06a74 - Get a specific types_receives by ID
func (s *TypesReceivesAPIService) F84e4922d0eeb8c8d92bcbf48af06a74(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update F84e4922d0eeb8c8d92bcbf48af06a74 with the required logic for this service method.
	// Add api_types_receives_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypeReceive{}) or use other options such as http.Ok ...
	// return Response(200, TypeReceive{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("F84e4922d0eeb8c8d92bcbf48af06a74 method not implemented")
}
