/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// BooksAPIService is a service that implements the logic for the BooksAPIServicer
// This service should implement the business logic for every endpoint for the BooksAPI API.
// Include any external packages or services that will be required by this service.
type BooksAPIService struct {
}

// NewBooksAPIService creates a default api service
func NewBooksAPIService() BooksAPIServicer {
	return &BooksAPIService{}
}

// Call14d04cd3a807843d383b87ccfca3da7b - 書籍の検索と支部在庫の表示
func (s *BooksAPIService) Call14d04cd3a807843d383b87ccfca3da7b(ctx context.Context, typeBranchId int32, q string, f int32, t int32) (ImplResponse, error) {
	// TODO - update Call14d04cd3a807843d383b87ccfca3da7b with the required logic for this service method.
	// Add api_books_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Model14d04cd3a807843d383b87ccfca3da7b200ResponseInner{}) or use other options such as http.Ok ...
	// return Response(200, []Model14d04cd3a807843d383b87ccfca3da7b200ResponseInner{}), nil

	// TODO: Uncomment the next line to return response Response(404, Model14d04cd3a807843d383b87ccfca3da7b404Response{}) or use other options such as http.Ok ...
	// return Response(404, Model14d04cd3a807843d383b87ccfca3da7b404Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call14d04cd3a807843d383b87ccfca3da7b method not implemented")
}

// Call24c56c274fc27bd118b5dfc62fbf0c3e - 書籍の検索と支部在庫の表示
func (s *BooksAPIService) Call24c56c274fc27bd118b5dfc62fbf0c3e(ctx context.Context, typeBranchId int32, id string, title string, author string, publisher string, genre string, description string) (ImplResponse, error) {
	// TODO - update Call24c56c274fc27bd118b5dfc62fbf0c3e with the required logic for this service method.
	// Add api_books_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Model14d04cd3a807843d383b87ccfca3da7b200ResponseInner{}) or use other options such as http.Ok ...
	// return Response(200, []Model14d04cd3a807843d383b87ccfca3da7b200ResponseInner{}), nil

	// TODO: Uncomment the next line to return response Response(404, Model14d04cd3a807843d383b87ccfca3da7b404Response{}) or use other options such as http.Ok ...
	// return Response(404, Model14d04cd3a807843d383b87ccfca3da7b404Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call24c56c274fc27bd118b5dfc62fbf0c3e method not implemented")
}
