/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// TypesGenresAPIService is a service that implements the logic for the TypesGenresAPIServicer
// This service should implement the business logic for every endpoint for the TypesGenresAPI API.
// Include any external packages or services that will be required by this service.
type TypesGenresAPIService struct {
}

// NewTypesGenresAPIService creates a default api service
func NewTypesGenresAPIService() TypesGenresAPIServicer {
	return &TypesGenresAPIService{}
}

// Call32a2a32ec50d514a9cc3ca51fb2d6578 - Update a specific types_genres by ID
func (s *TypesGenresAPIService) Call32a2a32ec50d514a9cc3ca51fb2d6578(ctx context.Context, id string, typeGenre TypeGenre) (ImplResponse, error) {
	// TODO - update Call32a2a32ec50d514a9cc3ca51fb2d6578 with the required logic for this service method.
	// Add api_types_genres_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypeGenre{}) or use other options such as http.Ok ...
	// return Response(200, TypeGenre{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call32a2a32ec50d514a9cc3ca51fb2d6578 method not implemented")
}

// Call5876eb953745b47325ca0277455f8885 - Create a new types_genres
func (s *TypesGenresAPIService) Call5876eb953745b47325ca0277455f8885(ctx context.Context, typeGenre TypeGenre) (ImplResponse, error) {
	// TODO - update Call5876eb953745b47325ca0277455f8885 with the required logic for this service method.
	// Add api_types_genres_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, TypeGenre{}) or use other options such as http.Ok ...
	// return Response(201, TypeGenre{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call5876eb953745b47325ca0277455f8885 method not implemented")
}

// Call6e1cdb613ad44750c97159198eac2c2e - Get a list of types_genres
func (s *TypesGenresAPIService) Call6e1cdb613ad44750c97159198eac2c2e(ctx context.Context) (ImplResponse, error) {
	// TODO - update Call6e1cdb613ad44750c97159198eac2c2e with the required logic for this service method.
	// Add api_types_genres_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []TypeGenre{}) or use other options such as http.Ok ...
	// return Response(200, []TypeGenre{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call6e1cdb613ad44750c97159198eac2c2e method not implemented")
}

// Call70509fad3bfe1e67a2caf35fe9ddcd88 - Get a specific types_genres by ID
func (s *TypesGenresAPIService) Call70509fad3bfe1e67a2caf35fe9ddcd88(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call70509fad3bfe1e67a2caf35fe9ddcd88 with the required logic for this service method.
	// Add api_types_genres_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TypeGenre{}) or use other options such as http.Ok ...
	// return Response(200, TypeGenre{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call70509fad3bfe1e67a2caf35fe9ddcd88 method not implemented")
}

// Call8ecb93fe6d9f820f901f57aaca0c8650 - Delete a specific types_genres by ID
func (s *TypesGenresAPIService) Call8ecb93fe6d9f820f901f57aaca0c8650(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call8ecb93fe6d9f820f901f57aaca0c8650 with the required logic for this service method.
	// Add api_types_genres_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call8ecb93fe6d9f820f901f57aaca0c8650 method not implemented")
}
