/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// TypesGenresAPIController binds http requests to an api service and writes the service results to the http response
type TypesGenresAPIController struct {
	service TypesGenresAPIServicer
	errorHandler ErrorHandler
}

// TypesGenresAPIOption for how the controller is set up.
type TypesGenresAPIOption func(*TypesGenresAPIController)

// WithTypesGenresAPIErrorHandler inject ErrorHandler into controller
func WithTypesGenresAPIErrorHandler(h ErrorHandler) TypesGenresAPIOption {
	return func(c *TypesGenresAPIController) {
		c.errorHandler = h
	}
}

// NewTypesGenresAPIController creates a default api controller
func NewTypesGenresAPIController(s TypesGenresAPIServicer, opts ...TypesGenresAPIOption) Router {
	controller := &TypesGenresAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TypesGenresAPIController
func (c *TypesGenresAPIController) Routes() Routes {
	return Routes{
		"Call32a2a32ec50d514a9cc3ca51fb2d6578": Route{
			strings.ToUpper("Put"),
			"/api/types_genres/{id}",
			c.Call32a2a32ec50d514a9cc3ca51fb2d6578,
		},
		"Call5876eb953745b47325ca0277455f8885": Route{
			strings.ToUpper("Post"),
			"/api/types_genres",
			c.Call5876eb953745b47325ca0277455f8885,
		},
		"Call6e1cdb613ad44750c97159198eac2c2e": Route{
			strings.ToUpper("Get"),
			"/api/types_genres",
			c.Call6e1cdb613ad44750c97159198eac2c2e,
		},
		"Call70509fad3bfe1e67a2caf35fe9ddcd88": Route{
			strings.ToUpper("Get"),
			"/api/types_genres/{id}",
			c.Call70509fad3bfe1e67a2caf35fe9ddcd88,
		},
		"Call8ecb93fe6d9f820f901f57aaca0c8650": Route{
			strings.ToUpper("Delete"),
			"/api/types_genres/{id}",
			c.Call8ecb93fe6d9f820f901f57aaca0c8650,
		},
	}
}

// Call32a2a32ec50d514a9cc3ca51fb2d6578 - Update a specific types_genres by ID
func (c *TypesGenresAPIController) Call32a2a32ec50d514a9cc3ca51fb2d6578(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	typeGenreParam := TypeGenre{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&typeGenreParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTypeGenreRequired(typeGenreParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTypeGenreConstraints(typeGenreParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call32a2a32ec50d514a9cc3ca51fb2d6578(r.Context(), idParam, typeGenreParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call5876eb953745b47325ca0277455f8885 - Create a new types_genres
func (c *TypesGenresAPIController) Call5876eb953745b47325ca0277455f8885(w http.ResponseWriter, r *http.Request) {
	typeGenreParam := TypeGenre{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&typeGenreParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTypeGenreRequired(typeGenreParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTypeGenreConstraints(typeGenreParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call5876eb953745b47325ca0277455f8885(r.Context(), typeGenreParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call6e1cdb613ad44750c97159198eac2c2e - Get a list of types_genres
func (c *TypesGenresAPIController) Call6e1cdb613ad44750c97159198eac2c2e(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Call6e1cdb613ad44750c97159198eac2c2e(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call70509fad3bfe1e67a2caf35fe9ddcd88 - Get a specific types_genres by ID
func (c *TypesGenresAPIController) Call70509fad3bfe1e67a2caf35fe9ddcd88(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Call70509fad3bfe1e67a2caf35fe9ddcd88(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call8ecb93fe6d9f820f901f57aaca0c8650 - Delete a specific types_genres by ID
func (c *TypesGenresAPIController) Call8ecb93fe6d9f820f901f57aaca0c8650(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Call8ecb93fe6d9f820f901f57aaca0c8650(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
