/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ContactsAPIService is a service that implements the logic for the ContactsAPIServicer
// This service should implement the business logic for every endpoint for the ContactsAPI API.
// Include any external packages or services that will be required by this service.
type ContactsAPIService struct {
}

// NewContactsAPIService creates a default api service
func NewContactsAPIService() ContactsAPIServicer {
	return &ContactsAPIService{}
}

// Adc814a54ff3a1fdc424293b19ffe8a7 - Update a specific contact by ID
func (s *ContactsAPIService) Adc814a54ff3a1fdc424293b19ffe8a7(ctx context.Context, id string, contact Contact) (ImplResponse, error) {
	// TODO - update Adc814a54ff3a1fdc424293b19ffe8a7 with the required logic for this service method.
	// Add api_contacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Contact{}) or use other options such as http.Ok ...
	// return Response(200, Contact{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Adc814a54ff3a1fdc424293b19ffe8a7 method not implemented")
}

// Bc8b0b91abd89481c321fcdb966dc355 - Delete a specific contact by ID
func (s *ContactsAPIService) Bc8b0b91abd89481c321fcdb966dc355(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Bc8b0b91abd89481c321fcdb966dc355 with the required logic for this service method.
	// Add api_contacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Bc8b0b91abd89481c321fcdb966dc355 method not implemented")
}

// Call4c4e002507e3a53acc022b210aad20ac - Get a specific contact by ID
func (s *ContactsAPIService) Call4c4e002507e3a53acc022b210aad20ac(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call4c4e002507e3a53acc022b210aad20ac with the required logic for this service method.
	// Add api_contacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Contact{}) or use other options such as http.Ok ...
	// return Response(200, Contact{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call4c4e002507e3a53acc022b210aad20ac method not implemented")
}

// Call77b53a0b0cb97bf04eafa192e4cbac4e - Create a new contact
func (s *ContactsAPIService) Call77b53a0b0cb97bf04eafa192e4cbac4e(ctx context.Context, contact Contact) (ImplResponse, error) {
	// TODO - update Call77b53a0b0cb97bf04eafa192e4cbac4e with the required logic for this service method.
	// Add api_contacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Contact{}) or use other options such as http.Ok ...
	// return Response(201, Contact{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call77b53a0b0cb97bf04eafa192e4cbac4e method not implemented")
}

// E670331f5da6af785062a857ec92def2 - Get a list of contacts
func (s *ContactsAPIService) E670331f5da6af785062a857ec92def2(ctx context.Context) (ImplResponse, error) {
	// TODO - update E670331f5da6af785062a857ec92def2 with the required logic for this service method.
	// Add api_contacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Contact{}) or use other options such as http.Ok ...
	// return Response(200, []Contact{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("E670331f5da6af785062a857ec92def2 method not implemented")
}
