/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// OrdersPaymentsAPIController binds http requests to an api service and writes the service results to the http response
type OrdersPaymentsAPIController struct {
	service OrdersPaymentsAPIServicer
	errorHandler ErrorHandler
}

// OrdersPaymentsAPIOption for how the controller is set up.
type OrdersPaymentsAPIOption func(*OrdersPaymentsAPIController)

// WithOrdersPaymentsAPIErrorHandler inject ErrorHandler into controller
func WithOrdersPaymentsAPIErrorHandler(h ErrorHandler) OrdersPaymentsAPIOption {
	return func(c *OrdersPaymentsAPIController) {
		c.errorHandler = h
	}
}

// NewOrdersPaymentsAPIController creates a default api controller
func NewOrdersPaymentsAPIController(s OrdersPaymentsAPIServicer, opts ...OrdersPaymentsAPIOption) Router {
	controller := &OrdersPaymentsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the OrdersPaymentsAPIController
func (c *OrdersPaymentsAPIController) Routes() Routes {
	return Routes{
		"Call231e4438ab66e1f3ba4205adf67e0df7": Route{
			strings.ToUpper("Post"),
			"/api/orders_payments",
			c.Call231e4438ab66e1f3ba4205adf67e0df7,
		},
		"Call41c8a438add65c3a1a6f1f7f0efeeea3": Route{
			strings.ToUpper("Delete"),
			"/api/orders_payments/{id}",
			c.Call41c8a438add65c3a1a6f1f7f0efeeea3,
		},
		"Call52140bdaf9965edfc692b030a9f1898f": Route{
			strings.ToUpper("Get"),
			"/api/orders_payments",
			c.Call52140bdaf9965edfc692b030a9f1898f,
		},
		"E7043bcd7e8fc712b2e3a6516f1b8ca8": Route{
			strings.ToUpper("Put"),
			"/api/orders_payments/{id}",
			c.E7043bcd7e8fc712b2e3a6516f1b8ca8,
		},
		"Ed63e750658440b279ee8040dc02aba5": Route{
			strings.ToUpper("Get"),
			"/api/orders_payments/{id}",
			c.Ed63e750658440b279ee8040dc02aba5,
		},
	}
}

// Call231e4438ab66e1f3ba4205adf67e0df7 - Create a new orders_payments
func (c *OrdersPaymentsAPIController) Call231e4438ab66e1f3ba4205adf67e0df7(w http.ResponseWriter, r *http.Request) {
	orderPaymentParam := OrderPayment{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&orderPaymentParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertOrderPaymentRequired(orderPaymentParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertOrderPaymentConstraints(orderPaymentParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call231e4438ab66e1f3ba4205adf67e0df7(r.Context(), orderPaymentParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call41c8a438add65c3a1a6f1f7f0efeeea3 - Delete a specific orders_payments by ID
func (c *OrdersPaymentsAPIController) Call41c8a438add65c3a1a6f1f7f0efeeea3(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Call41c8a438add65c3a1a6f1f7f0efeeea3(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call52140bdaf9965edfc692b030a9f1898f - Get a list of orders_payments
func (c *OrdersPaymentsAPIController) Call52140bdaf9965edfc692b030a9f1898f(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Call52140bdaf9965edfc692b030a9f1898f(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// E7043bcd7e8fc712b2e3a6516f1b8ca8 - Update a specific orders_payments by ID
func (c *OrdersPaymentsAPIController) E7043bcd7e8fc712b2e3a6516f1b8ca8(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	orderPaymentParam := OrderPayment{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&orderPaymentParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertOrderPaymentRequired(orderPaymentParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertOrderPaymentConstraints(orderPaymentParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.E7043bcd7e8fc712b2e3a6516f1b8ca8(r.Context(), idParam, orderPaymentParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Ed63e750658440b279ee8040dc02aba5 - Get a specific orders_payments by ID
func (c *OrdersPaymentsAPIController) Ed63e750658440b279ee8040dc02aba5(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Ed63e750658440b279ee8040dc02aba5(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
