/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// OrdersPaymentsAPIService is a service that implements the logic for the OrdersPaymentsAPIServicer
// This service should implement the business logic for every endpoint for the OrdersPaymentsAPI API.
// Include any external packages or services that will be required by this service.
type OrdersPaymentsAPIService struct {
}

// NewOrdersPaymentsAPIService creates a default api service
func NewOrdersPaymentsAPIService() OrdersPaymentsAPIServicer {
	return &OrdersPaymentsAPIService{}
}

// Call231e4438ab66e1f3ba4205adf67e0df7 - Create a new orders_payments
func (s *OrdersPaymentsAPIService) Call231e4438ab66e1f3ba4205adf67e0df7(ctx context.Context, orderPayment OrderPayment) (ImplResponse, error) {
	// TODO - update Call231e4438ab66e1f3ba4205adf67e0df7 with the required logic for this service method.
	// Add api_orders_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, OrderPayment{}) or use other options such as http.Ok ...
	// return Response(201, OrderPayment{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call231e4438ab66e1f3ba4205adf67e0df7 method not implemented")
}

// Call41c8a438add65c3a1a6f1f7f0efeeea3 - Delete a specific orders_payments by ID
func (s *OrdersPaymentsAPIService) Call41c8a438add65c3a1a6f1f7f0efeeea3(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call41c8a438add65c3a1a6f1f7f0efeeea3 with the required logic for this service method.
	// Add api_orders_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call41c8a438add65c3a1a6f1f7f0efeeea3 method not implemented")
}

// Call52140bdaf9965edfc692b030a9f1898f - Get a list of orders_payments
func (s *OrdersPaymentsAPIService) Call52140bdaf9965edfc692b030a9f1898f(ctx context.Context) (ImplResponse, error) {
	// TODO - update Call52140bdaf9965edfc692b030a9f1898f with the required logic for this service method.
	// Add api_orders_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []OrderPayment{}) or use other options such as http.Ok ...
	// return Response(200, []OrderPayment{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call52140bdaf9965edfc692b030a9f1898f method not implemented")
}

// E7043bcd7e8fc712b2e3a6516f1b8ca8 - Update a specific orders_payments by ID
func (s *OrdersPaymentsAPIService) E7043bcd7e8fc712b2e3a6516f1b8ca8(ctx context.Context, id string, orderPayment OrderPayment) (ImplResponse, error) {
	// TODO - update E7043bcd7e8fc712b2e3a6516f1b8ca8 with the required logic for this service method.
	// Add api_orders_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderPayment{}) or use other options such as http.Ok ...
	// return Response(200, OrderPayment{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("E7043bcd7e8fc712b2e3a6516f1b8ca8 method not implemented")
}

// Ed63e750658440b279ee8040dc02aba5 - Get a specific orders_payments by ID
func (s *OrdersPaymentsAPIService) Ed63e750658440b279ee8040dc02aba5(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Ed63e750658440b279ee8040dc02aba5 with the required logic for this service method.
	// Add api_orders_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderPayment{}) or use other options such as http.Ok ...
	// return Response(200, OrderPayment{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Ed63e750658440b279ee8040dc02aba5 method not implemented")
}
