/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// NewsAPIService is a service that implements the logic for the NewsAPIServicer
// This service should implement the business logic for every endpoint for the NewsAPI API.
// Include any external packages or services that will be required by this service.
type NewsAPIService struct {
}

// NewNewsAPIService creates a default api service
func NewNewsAPIService() NewsAPIServicer {
	return &NewsAPIService{}
}

// Bbe79a918bfbb58bc46ed74b43e9b986 - Delete a specific news by ID
func (s *NewsAPIService) Bbe79a918bfbb58bc46ed74b43e9b986(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Bbe79a918bfbb58bc46ed74b43e9b986 with the required logic for this service method.
	// Add api_news_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Bbe79a918bfbb58bc46ed74b43e9b986 method not implemented")
}

// Call21b84dbdd75fd20b9c9ddb9b9e68f0a1 - Get a list of news
func (s *NewsAPIService) Call21b84dbdd75fd20b9c9ddb9b9e68f0a1(ctx context.Context) (ImplResponse, error) {
	// TODO - update Call21b84dbdd75fd20b9c9ddb9b9e68f0a1 with the required logic for this service method.
	// Add api_news_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []News{}) or use other options such as http.Ok ...
	// return Response(200, []News{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call21b84dbdd75fd20b9c9ddb9b9e68f0a1 method not implemented")
}

// Call25ea273290c6cb379ab85e08ff4fadfc - Update a specific news by ID
func (s *NewsAPIService) Call25ea273290c6cb379ab85e08ff4fadfc(ctx context.Context, id string, news News) (ImplResponse, error) {
	// TODO - update Call25ea273290c6cb379ab85e08ff4fadfc with the required logic for this service method.
	// Add api_news_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, News{}) or use other options such as http.Ok ...
	// return Response(200, News{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call25ea273290c6cb379ab85e08ff4fadfc method not implemented")
}

// D6a12c2e3b4ea9ab588ba9b1cb14748f - Create a new news
func (s *NewsAPIService) D6a12c2e3b4ea9ab588ba9b1cb14748f(ctx context.Context, news News) (ImplResponse, error) {
	// TODO - update D6a12c2e3b4ea9ab588ba9b1cb14748f with the required logic for this service method.
	// Add api_news_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, News{}) or use other options such as http.Ok ...
	// return Response(201, News{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("D6a12c2e3b4ea9ab588ba9b1cb14748f method not implemented")
}

// Eb815321a4dd395639d4aeef25d9a45c - Get a specific news by ID
func (s *NewsAPIService) Eb815321a4dd395639d4aeef25d9a45c(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Eb815321a4dd395639d4aeef25d9a45c with the required logic for this service method.
	// Add api_news_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, News{}) or use other options such as http.Ok ...
	// return Response(200, News{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Eb815321a4dd395639d4aeef25d9a45c method not implemented")
}
