/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// TypesOrdersStatesAPIController binds http requests to an api service and writes the service results to the http response
type TypesOrdersStatesAPIController struct {
	service TypesOrdersStatesAPIServicer
	errorHandler ErrorHandler
}

// TypesOrdersStatesAPIOption for how the controller is set up.
type TypesOrdersStatesAPIOption func(*TypesOrdersStatesAPIController)

// WithTypesOrdersStatesAPIErrorHandler inject ErrorHandler into controller
func WithTypesOrdersStatesAPIErrorHandler(h ErrorHandler) TypesOrdersStatesAPIOption {
	return func(c *TypesOrdersStatesAPIController) {
		c.errorHandler = h
	}
}

// NewTypesOrdersStatesAPIController creates a default api controller
func NewTypesOrdersStatesAPIController(s TypesOrdersStatesAPIServicer, opts ...TypesOrdersStatesAPIOption) Router {
	controller := &TypesOrdersStatesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TypesOrdersStatesAPIController
func (c *TypesOrdersStatesAPIController) Routes() Routes {
	return Routes{
		"Call02b2536d5626b2b69c4eb31a6420a222": Route{
			strings.ToUpper("Post"),
			"/api/types_orders_states",
			c.Call02b2536d5626b2b69c4eb31a6420a222,
		},
		"Call035007899d1aeec37cb670bb3c8a4865": Route{
			strings.ToUpper("Delete"),
			"/api/types_orders_states/{id}",
			c.Call035007899d1aeec37cb670bb3c8a4865,
		},
		"Call629ceee33a2f3da61afd7c4b1e462219": Route{
			strings.ToUpper("Get"),
			"/api/types_orders_states",
			c.Call629ceee33a2f3da61afd7c4b1e462219,
		},
		"F264dd50d2da88f988e3a8e7c592d301": Route{
			strings.ToUpper("Get"),
			"/api/types_orders_states/{id}",
			c.F264dd50d2da88f988e3a8e7c592d301,
		},
		"F8e23ef739c0f341106a112ecde4ad7e": Route{
			strings.ToUpper("Put"),
			"/api/types_orders_states/{id}",
			c.F8e23ef739c0f341106a112ecde4ad7e,
		},
	}
}

// Call02b2536d5626b2b69c4eb31a6420a222 - Create a new types_orders_states
func (c *TypesOrdersStatesAPIController) Call02b2536d5626b2b69c4eb31a6420a222(w http.ResponseWriter, r *http.Request) {
	typeOrderStateParam := TypeOrderState{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&typeOrderStateParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTypeOrderStateRequired(typeOrderStateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTypeOrderStateConstraints(typeOrderStateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call02b2536d5626b2b69c4eb31a6420a222(r.Context(), typeOrderStateParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call035007899d1aeec37cb670bb3c8a4865 - Delete a specific types_orders_states by ID
func (c *TypesOrdersStatesAPIController) Call035007899d1aeec37cb670bb3c8a4865(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Call035007899d1aeec37cb670bb3c8a4865(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call629ceee33a2f3da61afd7c4b1e462219 - Get a list of types_orders_states
func (c *TypesOrdersStatesAPIController) Call629ceee33a2f3da61afd7c4b1e462219(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Call629ceee33a2f3da61afd7c4b1e462219(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// F264dd50d2da88f988e3a8e7c592d301 - Get a specific types_orders_states by ID
func (c *TypesOrdersStatesAPIController) F264dd50d2da88f988e3a8e7c592d301(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.F264dd50d2da88f988e3a8e7c592d301(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// F8e23ef739c0f341106a112ecde4ad7e - Update a specific types_orders_states by ID
func (c *TypesOrdersStatesAPIController) F8e23ef739c0f341106a112ecde4ad7e(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	typeOrderStateParam := TypeOrderState{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&typeOrderStateParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTypeOrderStateRequired(typeOrderStateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTypeOrderStateConstraints(typeOrderStateParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.F8e23ef739c0f341106a112ecde4ad7e(r.Context(), idParam, typeOrderStateParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
