/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// TypesPaymentsAPIController binds http requests to an api service and writes the service results to the http response
type TypesPaymentsAPIController struct {
	service TypesPaymentsAPIServicer
	errorHandler ErrorHandler
}

// TypesPaymentsAPIOption for how the controller is set up.
type TypesPaymentsAPIOption func(*TypesPaymentsAPIController)

// WithTypesPaymentsAPIErrorHandler inject ErrorHandler into controller
func WithTypesPaymentsAPIErrorHandler(h ErrorHandler) TypesPaymentsAPIOption {
	return func(c *TypesPaymentsAPIController) {
		c.errorHandler = h
	}
}

// NewTypesPaymentsAPIController creates a default api controller
func NewTypesPaymentsAPIController(s TypesPaymentsAPIServicer, opts ...TypesPaymentsAPIOption) Router {
	controller := &TypesPaymentsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TypesPaymentsAPIController
func (c *TypesPaymentsAPIController) Routes() Routes {
	return Routes{
		"Call15eb6d8e179f295d0df87be744c28155": Route{
			strings.ToUpper("Get"),
			"/api/types_payments/{id}",
			c.Call15eb6d8e179f295d0df87be744c28155,
		},
		"Call9dd9af2fc19d3f1e1688cf1b0528218b": Route{
			strings.ToUpper("Put"),
			"/api/types_payments/{id}",
			c.Call9dd9af2fc19d3f1e1688cf1b0528218b,
		},
		"E757690d6c96a1463bd2f8fce9b45b12": Route{
			strings.ToUpper("Post"),
			"/api/types_payments",
			c.E757690d6c96a1463bd2f8fce9b45b12,
		},
		"E83a182945610fbcf279008b97e0de46": Route{
			strings.ToUpper("Delete"),
			"/api/types_payments/{id}",
			c.E83a182945610fbcf279008b97e0de46,
		},
		"Eaf58772b330330fc4d41fc0e8b3b40f": Route{
			strings.ToUpper("Get"),
			"/api/types_payments",
			c.Eaf58772b330330fc4d41fc0e8b3b40f,
		},
	}
}

// Call15eb6d8e179f295d0df87be744c28155 - Get a specific types_payments by ID
func (c *TypesPaymentsAPIController) Call15eb6d8e179f295d0df87be744c28155(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.Call15eb6d8e179f295d0df87be744c28155(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call9dd9af2fc19d3f1e1688cf1b0528218b - Update a specific types_payments by ID
func (c *TypesPaymentsAPIController) Call9dd9af2fc19d3f1e1688cf1b0528218b(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	typePaymentParam := TypePayment{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&typePaymentParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTypePaymentRequired(typePaymentParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTypePaymentConstraints(typePaymentParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call9dd9af2fc19d3f1e1688cf1b0528218b(r.Context(), idParam, typePaymentParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// E757690d6c96a1463bd2f8fce9b45b12 - Create a new types_payments
func (c *TypesPaymentsAPIController) E757690d6c96a1463bd2f8fce9b45b12(w http.ResponseWriter, r *http.Request) {
	typePaymentParam := TypePayment{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&typePaymentParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTypePaymentRequired(typePaymentParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTypePaymentConstraints(typePaymentParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.E757690d6c96a1463bd2f8fce9b45b12(r.Context(), typePaymentParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// E83a182945610fbcf279008b97e0de46 - Delete a specific types_payments by ID
func (c *TypesPaymentsAPIController) E83a182945610fbcf279008b97e0de46(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.E83a182945610fbcf279008b97e0de46(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Eaf58772b330330fc4d41fc0e8b3b40f - Get a list of types_payments
func (c *TypesPaymentsAPIController) Eaf58772b330330fc4d41fc0e8b3b40f(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Eaf58772b330330fc4d41fc0e8b3b40f(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
