/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// TypesReceivesAPIController binds http requests to an api service and writes the service results to the http response
type TypesReceivesAPIController struct {
	service TypesReceivesAPIServicer
	errorHandler ErrorHandler
}

// TypesReceivesAPIOption for how the controller is set up.
type TypesReceivesAPIOption func(*TypesReceivesAPIController)

// WithTypesReceivesAPIErrorHandler inject ErrorHandler into controller
func WithTypesReceivesAPIErrorHandler(h ErrorHandler) TypesReceivesAPIOption {
	return func(c *TypesReceivesAPIController) {
		c.errorHandler = h
	}
}

// NewTypesReceivesAPIController creates a default api controller
func NewTypesReceivesAPIController(s TypesReceivesAPIServicer, opts ...TypesReceivesAPIOption) Router {
	controller := &TypesReceivesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TypesReceivesAPIController
func (c *TypesReceivesAPIController) Routes() Routes {
	return Routes{
		"B1a600a99289da180209079339415e49": Route{
			strings.ToUpper("Delete"),
			"/api/types_receives/{id}",
			c.B1a600a99289da180209079339415e49,
		},
		"C1543df8694acb50827b80eb08cd5b4a": Route{
			strings.ToUpper("Put"),
			"/api/types_receives/{id}",
			c.C1543df8694acb50827b80eb08cd5b4a,
		},
		"Call0417ea5e25bfb8fd8ee49856f17016fa": Route{
			strings.ToUpper("Get"),
			"/api/types_receives",
			c.Call0417ea5e25bfb8fd8ee49856f17016fa,
		},
		"Call50090e82cc0eacb3d7b613a9ff868b17": Route{
			strings.ToUpper("Post"),
			"/api/types_receives",
			c.Call50090e82cc0eacb3d7b613a9ff868b17,
		},
		"F84e4922d0eeb8c8d92bcbf48af06a74": Route{
			strings.ToUpper("Get"),
			"/api/types_receives/{id}",
			c.F84e4922d0eeb8c8d92bcbf48af06a74,
		},
	}
}

// B1a600a99289da180209079339415e49 - Delete a specific types_receives by ID
func (c *TypesReceivesAPIController) B1a600a99289da180209079339415e49(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.B1a600a99289da180209079339415e49(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// C1543df8694acb50827b80eb08cd5b4a - Update a specific types_receives by ID
func (c *TypesReceivesAPIController) C1543df8694acb50827b80eb08cd5b4a(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	typeReceiveParam := TypeReceive{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&typeReceiveParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTypeReceiveRequired(typeReceiveParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTypeReceiveConstraints(typeReceiveParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.C1543df8694acb50827b80eb08cd5b4a(r.Context(), idParam, typeReceiveParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call0417ea5e25bfb8fd8ee49856f17016fa - Get a list of types_receives
func (c *TypesReceivesAPIController) Call0417ea5e25bfb8fd8ee49856f17016fa(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Call0417ea5e25bfb8fd8ee49856f17016fa(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// Call50090e82cc0eacb3d7b613a9ff868b17 - Create a new types_receives
func (c *TypesReceivesAPIController) Call50090e82cc0eacb3d7b613a9ff868b17(w http.ResponseWriter, r *http.Request) {
	typeReceiveParam := TypeReceive{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&typeReceiveParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTypeReceiveRequired(typeReceiveParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTypeReceiveConstraints(typeReceiveParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Call50090e82cc0eacb3d7b613a9ff868b17(r.Context(), typeReceiveParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// F84e4922d0eeb8c8d92bcbf48af06a74 - Get a specific types_receives by ID
func (c *TypesReceivesAPIController) F84e4922d0eeb8c8d92bcbf48af06a74(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam := params["id"]
	result, err := c.service.F84e4922d0eeb8c8d92bcbf48af06a74(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
