/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// OrdersItemsAPIService is a service that implements the logic for the OrdersItemsAPIServicer
// This service should implement the business logic for every endpoint for the OrdersItemsAPI API.
// Include any external packages or services that will be required by this service.
type OrdersItemsAPIService struct {
}

// NewOrdersItemsAPIService creates a default api service
func NewOrdersItemsAPIService() OrdersItemsAPIServicer {
	return &OrdersItemsAPIService{}
}

// B2909cc3849277b1d5345ccb4205c71d - Create a new orders_items
func (s *OrdersItemsAPIService) B2909cc3849277b1d5345ccb4205c71d(ctx context.Context, orderItem OrderItem) (ImplResponse, error) {
	// TODO - update B2909cc3849277b1d5345ccb4205c71d with the required logic for this service method.
	// Add api_orders_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, OrderItem{}) or use other options such as http.Ok ...
	// return Response(201, OrderItem{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("B2909cc3849277b1d5345ccb4205c71d method not implemented")
}

// Call0b2a7a56e7d5c2c49b7d11bdb0f48f5c - Get a specific orders_items by ID
func (s *OrdersItemsAPIService) Call0b2a7a56e7d5c2c49b7d11bdb0f48f5c(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call0b2a7a56e7d5c2c49b7d11bdb0f48f5c with the required logic for this service method.
	// Add api_orders_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderItem{}) or use other options such as http.Ok ...
	// return Response(200, OrderItem{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call0b2a7a56e7d5c2c49b7d11bdb0f48f5c method not implemented")
}

// Call6d397dbc3afd3a3f44e4cc08820e0921 - Delete a specific orders_items by ID
func (s *OrdersItemsAPIService) Call6d397dbc3afd3a3f44e4cc08820e0921(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Call6d397dbc3afd3a3f44e4cc08820e0921 with the required logic for this service method.
	// Add api_orders_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call6d397dbc3afd3a3f44e4cc08820e0921 method not implemented")
}

// Call89fde6ad08076b992c521fb7c680e29e - Get a list of orders_items
func (s *OrdersItemsAPIService) Call89fde6ad08076b992c521fb7c680e29e(ctx context.Context) (ImplResponse, error) {
	// TODO - update Call89fde6ad08076b992c521fb7c680e29e with the required logic for this service method.
	// Add api_orders_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []OrderItem{}) or use other options such as http.Ok ...
	// return Response(200, []OrderItem{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call89fde6ad08076b992c521fb7c680e29e method not implemented")
}

// Call8bee2e95aba24db3af9b2bc7b5a53f0d - Update a specific orders_items by ID
func (s *OrdersItemsAPIService) Call8bee2e95aba24db3af9b2bc7b5a53f0d(ctx context.Context, id string, orderItem OrderItem) (ImplResponse, error) {
	// TODO - update Call8bee2e95aba24db3af9b2bc7b5a53f0d with the required logic for this service method.
	// Add api_orders_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderItem{}) or use other options such as http.Ok ...
	// return Response(200, OrderItem{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Call8bee2e95aba24db3af9b2bc7b5a53f0d method not implemented")
}
