/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// TypeBranch - TypeBranch Model
type TypeBranch struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// 支部名
	Type string `json:"type,omitempty"`

	// レコード作成日
	CreatedAt time.Time `json:"created_at,omitempty"`

	// レコード更新日
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertTypeBranchRequired checks if the required fields are not zero-ed
func AssertTypeBranchRequired(obj TypeBranch) error {
	return nil
}

// AssertTypeBranchConstraints checks if the values respects the defined constraints
func AssertTypeBranchConstraints(obj TypeBranch) error {
	return nil
}
