/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// OrderItem - OrderItem Model
type OrderItem struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// 外部キー制約（orders_customersテーブル）
	OrderCustomerId int64 `json:"order_customer_id,omitempty"`

	// 整理番号
	Numbering string `json:"numbering,omitempty"`

	// 予約の処理状態を表すステータス。types_orders_statesテーブルから取得
	TypeOrderStateId int64 `json:"type_order_state_id,omitempty"`

	// 外部キー制約（books_info）
	BookInfoId int64 `json:"book_info_id,omitempty"`

	// ISBN-13 or ISBN-10
	Isbn string `json:"isbn,omitempty"`

	// タイトル
	Title string `json:"title,omitempty"`

	// 販売額
	SalePrice int64 `json:"sale_price,omitempty"`

	// レコード作成日
	CreatedAt time.Time `json:"created_at,omitempty"`

	// レコード更新日
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertOrderItemRequired checks if the required fields are not zero-ed
func AssertOrderItemRequired(obj OrderItem) error {
	return nil
}

// AssertOrderItemConstraints checks if the values respects the defined constraints
func AssertOrderItemConstraints(obj OrderItem) error {
	return nil
}
