/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type 14d04cd3a807843d383b87ccfca3da7b200ResponseInner struct {

	BooksInfo BookInfo `json:"books_info,omitempty"`

	BooksStocks BookStock `json:"books_stocks,omitempty"`
}

// Assert14d04cd3a807843d383b87ccfca3da7b200ResponseInnerRequired checks if the required fields are not zero-ed
func Assert14d04cd3a807843d383b87ccfca3da7b200ResponseInnerRequired(obj 14d04cd3a807843d383b87ccfca3da7b200ResponseInner) error {
	if err := AssertBookInfoRequired(obj.BooksInfo); err != nil {
		return err
	}
	if err := AssertBookStockRequired(obj.BooksStocks); err != nil {
		return err
	}
	return nil
}

// Assert14d04cd3a807843d383b87ccfca3da7b200ResponseInnerConstraints checks if the values respects the defined constraints
func Assert14d04cd3a807843d383b87ccfca3da7b200ResponseInnerConstraints(obj 14d04cd3a807843d383b87ccfca3da7b200ResponseInner) error {
	return nil
}
