/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// Contact - Contact Model
type Contact struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// お問い合わせ番号として相手に送信する一意な値
	Unique string `json:"unique,omitempty"`

	// 名前
	Name string `json:"name,omitempty"`

	// 所属
	Belong string `json:"belong,omitempty"`

	// メールアドレス
	Email string `json:"email,omitempty"`

	// 概要
	Summary string `json:"summary,omitempty"`

	// 詳細
	Detail string `json:"detail,omitempty"`

	// レコード作成日
	CreatedAt time.Time `json:"created_at,omitempty"`

	// レコード更新日
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertContactRequired checks if the required fields are not zero-ed
func AssertContactRequired(obj Contact) error {
	return nil
}

// AssertContactConstraints checks if the values respects the defined constraints
func AssertContactConstraints(obj Contact) error {
	return nil
}
