/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// OrderPayment - OrderPayment Model
type OrderPayment struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// 外部キー制約（orders_customersテーブル）
	OrderCustomerId int64 `json:"order_customer_id,omitempty"`

	// 整理番号
	Numbering string `json:"numbering,omitempty"`

	// 教科書代の小計
	Subtotal int64 `json:"subtotal,omitempty"`

	// 送料
	Postage int64 `json:"postage,omitempty"`

	// 手数料
	Fee int64 `json:"fee,omitempty"`

	// 支払い済みか
	IsPaid bool `json:"is_paid,omitempty"`

	// レコード作成日
	CreatedAt time.Time `json:"created_at,omitempty"`

	// レコード更新日
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertOrderPaymentRequired checks if the required fields are not zero-ed
func AssertOrderPaymentRequired(obj OrderPayment) error {
	return nil
}

// AssertOrderPaymentConstraints checks if the values respects the defined constraints
func AssertOrderPaymentConstraints(obj OrderPayment) error {
	return nil
}
