/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type 14d04cd3a807843d383b87ccfca3da7b404Response struct {

	Message string `json:"message,omitempty"`
}

// Assert14d04cd3a807843d383b87ccfca3da7b404ResponseRequired checks if the required fields are not zero-ed
func Assert14d04cd3a807843d383b87ccfca3da7b404ResponseRequired(obj 14d04cd3a807843d383b87ccfca3da7b404Response) error {
	return nil
}

// Assert14d04cd3a807843d383b87ccfca3da7b404ResponseConstraints checks if the values respects the defined constraints
func Assert14d04cd3a807843d383b87ccfca3da7b404ResponseConstraints(obj 14d04cd3a807843d383b87ccfca3da7b404Response) error {
	return nil
}
