/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// TypeReceive - TypeReceive Model
type TypeReceive struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// 受取り方法
	Type string `json:"type,omitempty"`

	// レコード作成日
	CreatedAt time.Time `json:"created_at,omitempty"`

	// レコード更新日
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertTypeReceiveRequired checks if the required fields are not zero-ed
func AssertTypeReceiveRequired(obj TypeReceive) error {
	return nil
}

// AssertTypeReceiveConstraints checks if the values respects the defined constraints
func AssertTypeReceiveConstraints(obj TypeReceive) error {
	return nil
}
