/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type 0c3283a323f1a4a3e81dbd5915be7518201Response struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// ISBN-13 or ISBN-10
	Isbn string `json:"isbn,omitempty"`

	// タイトル
	Title string `json:"title,omitempty"`

	// 著者
	Author string `json:"author,omitempty"`

	// 出版社
	Publisher string `json:"publisher,omitempty"`

	// ジャンル
	Genre string `json:"genre,omitempty"`

	// 定価
	ListPrice int64 `json:"list_price,omitempty"`

	// 販売額
	SalePrice int64 `json:"sale_price,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// Assert0c3283a323f1a4a3e81dbd5915be7518201ResponseRequired checks if the required fields are not zero-ed
func Assert0c3283a323f1a4a3e81dbd5915be7518201ResponseRequired(obj 0c3283a323f1a4a3e81dbd5915be7518201Response) error {
	return nil
}

// Assert0c3283a323f1a4a3e81dbd5915be7518201ResponseConstraints checks if the values respects the defined constraints
func Assert0c3283a323f1a4a3e81dbd5915be7518201ResponseConstraints(obj 0c3283a323f1a4a3e81dbd5915be7518201Response) error {
	return nil
}
