/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type Ecc649eea287e26856100c11f96bb3b9201Response struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// 外部キー制約（types_branchesテーブル）
	TypeBranchId int64 `json:"type_branch_id,omitempty"`

	// 外部キー制約（books_infoテーブル）
	BookInfoId int64 `json:"book_info_id,omitempty"`

	// 未販売の在庫数
	Stock int64 `json:"stock,omitempty"`

	// 未処理の予約数
	Order int64 `json:"order,omitempty"`

	// 販売済みの在庫数
	Sold int64 `json:"sold,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertEcc649eea287e26856100c11f96bb3b9201ResponseRequired checks if the required fields are not zero-ed
func AssertEcc649eea287e26856100c11f96bb3b9201ResponseRequired(obj Ecc649eea287e26856100c11f96bb3b9201Response) error {
	return nil
}

// AssertEcc649eea287e26856100c11f96bb3b9201ResponseConstraints checks if the values respects the defined constraints
func AssertEcc649eea287e26856100c11f96bb3b9201ResponseConstraints(obj Ecc649eea287e26856100c11f96bb3b9201Response) error {
	return nil
}
