/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// BookInfo - BookInfo Model
type BookInfo struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// ISBN-13 or ISBN-10
	Isbn string `json:"isbn,omitempty"`

	// タイトル
	Title string `json:"title,omitempty"`

	// 著者
	Author string `json:"author,omitempty"`

	// 出版社
	Publisher string `json:"publisher,omitempty"`

	// ジャンル
	Genre string `json:"genre,omitempty"`

	// 定価
	ListPrice int64 `json:"list_price,omitempty"`

	// 販売額
	SalePrice int64 `json:"sale_price,omitempty"`

	// レコード作成日
	CreatedAt time.Time `json:"created_at,omitempty"`

	// レコード更新日
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertBookInfoRequired checks if the required fields are not zero-ed
func AssertBookInfoRequired(obj BookInfo) error {
	return nil
}

// AssertBookInfoConstraints checks if the values respects the defined constraints
func AssertBookInfoConstraints(obj BookInfo) error {
	return nil
}
