/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// News - News Model
type News struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// ニュースのタイトル
	Title string `json:"title,omitempty"`

	// ニュースの記事
	Detail string `json:"detail,omitempty"`

	// レコード作成日
	CreatedAt time.Time `json:"created_at,omitempty"`

	// レコード更新日
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertNewsRequired checks if the required fields are not zero-ed
func AssertNewsRequired(obj News) error {
	return nil
}

// AssertNewsConstraints checks if the values respects the defined constraints
func AssertNewsConstraints(obj News) error {
	return nil
}
