/*
 * omu-rest
 *
 * Laravel製RESTful APIサーバー。著者: [connect0459](https://github.com/connect0459)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// OrderCustomer - OrderCustomer Model
type OrderCustomer struct {

	// ID
	Id int64 `json:"id,omitempty"`

	// 支部番号（types_branchesテーブルからの外部キー制約）
	TypeBranchId int64 `json:"type_branch_id,omitempty"`

	// 整理番号
	Numbering string `json:"numbering,omitempty"`

	// 名前
	Name1 string `json:"name1,omitempty"`

	// フリガナ or ローマ字
	Name2 string `json:"name2,omitempty"`

	// 大学
	University string `json:"university,omitempty"`

	// 学年
	Grade string `json:"grade,omitempty"`

	// 学科など
	Belong string `json:"belong,omitempty"`

	// メールアドレス
	Email string `json:"email,omitempty"`

	// 請求合計金額
	Total int64 `json:"total,omitempty"`

	// 受取り方法分類id（types_receivesテーブルからの外部キー制約）
	TypeReceiveId int64 `json:"type_receive_id,omitempty"`

	// 受取り日時
	ReceiveDate time.Time `json:"receive_date,omitempty"`

	// 支払い方法分類id（types_paymentsテーブルからの外部キー制約）
	TypePaymentId int64 `json:"type_payment_id,omitempty"`

	// 支払い期限
	PaymentDueDate time.Time `json:"payment_due_date,omitempty"`

	// 備考・質問
	Notes string `json:"notes,omitempty"`

	// レコード作成日
	CreatedAt time.Time `json:"created_at,omitempty"`

	// レコード更新日
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// AssertOrderCustomerRequired checks if the required fields are not zero-ed
func AssertOrderCustomerRequired(obj OrderCustomer) error {
	return nil
}

// AssertOrderCustomerConstraints checks if the values respects the defined constraints
func AssertOrderCustomerConstraints(obj OrderCustomer) error {
	return nil
}
